[graph]
all-features = true

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = [{ name = "cpufeatures", version = "0.2.17" }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
