[package]
name = "pb-runtime-secure"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
curve25519-dalek.workspace = true
pb-pbmux = { path = "../pb-pbmux" }
pb-secure = { path = "../pb-secure" }
pb-types = { path = "../pb-types" }
rustix = { workspace = true, features = ["fs", "process"] }
serde_json.workspace = true
snow.workspace = true
